[theme]
primaryColor = "#06b6d4"
backgroundColor = "#080b11"
secondaryBackgroundColor = "#0b0f17"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
